version: '3.7'
services:
  cypress_test:
    image: cypress_compose
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - ./dockerReports:/app/cypress/results
      - ./dockerReports:/app/mochawesome-report
